### Recipes Index
GET http://localhost:3000/recipes?search=sandwich

### Recipes Create
POST http://localhost:3000/recipes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMxNDUxMDV9.F0HZqOvMP8nvmq0IDE3jZB8q0f4MVvVCIi4Kw75N-VU

{
  "title": "Tofu Bibimbap",
  "ingredients": "Lots of fresh vegetables, rice, tofu, egg",
  "directions": "Mix all together with spicy sauce",
  "prep_time": 10
}

### Recipes Show
GET http://localhost:3000/recipes/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDMxNDAzNjV9.5Pi8UE1Z8DDJniq-Ia6-_dlS_47si9AZiet4sZ1GM78

### Recipes Update
PATCH http://localhost:3000/recipes/2
Content-Type: application/json

{
  "image_url": "https://cdn.britannica.com/14/198514-050-72C159BB/Ice-Cube-2015.jpg"
}

### Recipes Destroy
DELETE http://localhost:3000/recipes/4


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Cheddar",
  "email": "cheddar@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "cheddar@gmail.com",
  "password": "password"
}