### Recipes Index
GET http://localhost:3000/recipes?search=sandwich

### Recipes Create
POST http://localhost:3000/recipes
Content-Type: application/json

{
  "title": "Coffee",
  "chef": "Dani Zaghian",
  "ingredients": "Coffee beans",
  "directions": "Grind beans and brew coffee",
  "prep_time": 5
}

### Recipes Show
GET http://localhost:3000/recipes/6

### Recipes Update
PATCH http://localhost:3000/recipes/2
Content-Type: application/json

{
  "image_url": "https://cdn.britannica.com/14/198514-050-72C159BB/Ice-Cube-2015.jpg"
}

### Recipes Destroy
DELETE http://localhost:3000/recipes/4


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Cheddar",
  "email": "cheddar@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "asdf@gmail.com",
  "password": "asdf"
}